service: serverless-common-web-template

plugins:
  - serverless-plugin-scripts
custom:
  scripts:
    hooks:
      #'before:deploy:deploy': 'npm run build:ssr' # build both app and sever
      'deploy:finalize': 'node helper/assetsUploader.js' # upload assets to s3
      
resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          PriceClass: PriceClass_100
          ViewerCertificate:
            CloudFrontDefaultCertificate: false
            AcmCertificateArn: arn:aws:acm:us-east-1:545902454044:certificate/d1c221ec-bb65-4dbc-b3be-ae4d1a4ca895
          Aliases:
            - fashion.yati-trend.com

provider:
  name: aws
  cloudFront:
    cachePolicies:
      myCachePolicy:
        MinTTL: 0
        MaxTTL: 86000
        DefaultTTL: 3600
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none # Possible values are 'none', 'whitelist', 'allExcept' and 'all'
          EnableAcceptEncodingBrotli: true # optional
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - Host
          QueryStringsConfig:
            QueryStringBehavior: none # Possible values are 'none', 'whitelist', 'allExcept' and 'all'

package:
  exclude:
  - src/**
  - node_modules/**
  - e2e/**
  - coverage/**
  - '**/assets/**'
  - '**.json'
  - '!node_modules/aws-serverless-express-edge/**'
  - '!node_modules/qs/**'
  - '!node_modules/binary-case/**'
  - '!node_modules/type-is/**'
  - '!node_modules/media-typer/**'
  - '!node_modules/mime-types/**'
  - '!node_modules/mime-db/**'

functions:
  myLambdaAtEdge:
    handler: lambda.ssrserverless
    memorySize: 1024
    timeout: 3
    runtime: nodejs12.x
    events:
      - cloudFront:
          eventType: origin-response
          pathPattern: '*.*'
          origin: s3://adugu-testing.s3.amazonaws.com/webAssets
          cachePolicy:
            name: myCachePolicy
          behavior:
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - 'GET'
              - 'HEAD'
            CachedMethods:
              - 'GET'
              - 'HEAD'
      - cloudFront:
          eventType: origin-request
          origin: s3://adugu-testing.s3.amazonaws.com/webAssets
          cachePolicy:
            name: myCachePolicy
          behavior:
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - 'GET'
              - 'HEAD'
            CachedMethods:
              - 'GET'
              - 'HEAD'

    